services:
  k6:
    # 공식 k6 도커 이미지를 사용합니다.
    image: grafana/k6

    # k6 컨테이너가 시작될 때 실행할 명령어를 지정합니다.
    # /scripts/script.js 파일을 실행하라는 의미입니다.
    entrypoint: tail -f /dev/null

    # 호스트 PC의 ./scripts 폴더를 컨테이너 내부의 /scripts 폴더에 연결(마운트)합니다.
    # 이렇게 해야 컨테이너가 script.js 파일을 읽을 수 있습니다.
    volumes:
      - ./src/k6Test:/scripts

    # 컨테이너가 host.docker.internal 주소를 찾을 수 있도록 설정합니다.
    # host-gateway는 호스트 머신의 IP를 의미하는 특별한 값입니다.
    extra_hosts:
      - "host.docker.internal:host-gateway"